export const BRAND: string = process.env.NEXT_PUBLIC_BRAND || ''
export const BRAND_TAGLINE: string = process.env.NEXT_PUBLIC_BRAND_TAGLINE || ''
export const BRAND_TAGLINE_HERO_1: string = process.env.NEXT_PUBLIC_BRAND_TAGLINE_HERO_1 || ''
export const BRAND_TAGLINE_HERO_2: string = process.env.NEXT_PUBLIC_BRAND_TAGLINE_HERO_2 || ''
export const BRAND_TAGLINE_LONG: string = process.env.NEXT_PUBLIC_BRAND_TAGLINE_LONG || ''
